name: sysinfo

on:
  workflow_dispatch:


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: main
        run: |
          sudo apt update
          sudo apt install -y neofetch
          neofetch
          df -h
    
